### ISSUE TITLE
Add models from suggestive contours reference?

### ISSUE THREAD

**Issue by hertzmann** [alecjacobson/common-3d-test-models#1]
Some of these might be relevant:
https://gfx.cs.princeton.edu/proj/sugcon/models/

We use the cow and horse a lot in line drawing papers. I think I've seen Igea in a lot of papers.

**Comment by alecjacobson** [comment]
Great idea. I added the cow, horse and max (still missing some info).

I plan to get to all the Stanford ones eventually.
